export const initialData = [
  { id: 1, firstName: "John", lastName: "Doe", age: 30, city: "New York" },
  { id: 2, firstName: "Jane", lastName: "Smith", age: 24, city: "Los Angeles" },
  { id: 3, firstName: "Peter", lastName: "Jones", age: 45, city: "Chicago" },
  { id: 4, firstName: "Alice", lastName: "Williams", age: 28, city: "Houston" },
  { id: 5, firstName: "Bob", lastName: "Brown", age: 37, city: "Phoenix" },
  {
    id: 6,
    firstName: "Charlie",
    lastName: "Davis",
    age: 19,
    city: "Philadelphia",
  },
  {
    id: 7,
    firstName: "Diana",
    lastName: "Miller",
    age: 33,
    city: "San Antonio",
  },
  { id: 8, firstName: "Eve", lastName: "Garcia", age: 29, city: "San Diego" },
  { id: 9, firstName: "Frank", lastName: "Rodriguez", age: 50, city: "Dallas" },
  {
    id: 10,
    firstName: "Grace",
    lastName: "Martinez",
    age: 22,
    city: "San Jose",
  },
  {
    id: 11,
    firstName: "Heidi",
    lastName: "Hernandez",
    age: 41,
    city: "Austin",
  },
  {
    id: 12,
    firstName: "Ivan",
    lastName: "Lopez",
    age: 36,
    city: "Jacksonville",
  },
  {
    id: 13,
    firstName: "Judy",
    lastName: "Gonzalez",
    age: 27,
    city: "Fort Worth",
  },
  { id: 14, firstName: "Kevin", lastName: "Wilson", age: 31, city: "Columbus" },
  {
    id: 15,
    firstName: "Liam",
    lastName: "Anderson",
    age: 26,
    city: "Charlotte",
  },
];
